export const Games = [
    {
        imgUrl:"/assets/games/1.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true
    },
    {
        imgUrl:"/assets/games/2.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: false,
        isDiscounted: true, 
        isLive: false,
        hasDemo: true
    },
    {
        imgUrl:"/assets/games/3.webp",
        provider: "PLAY'N GO",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true
    },
    {
        imgUrl:"/assets/games/4.webp",
        provider: "SPRIBE",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true
    },
    {
        imgUrl:"/assets/games/5.webp",
        provider: "TURBO GAMES",
        isHot: false,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/6.webp",
        provider: "VELIPLAY",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/7.webp",
        provider: "100HP GAMING",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/8.webp",
        provider: "AVIATRIX",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/9.webp",
        provider: "VELIPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/10.webp",
        provider: "VELIPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/11.webp",
        provider: "EZUGI",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: false,
    },
    {
        imgUrl:"/assets/games/12.webp",
        provider: "TOPSPIN",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: false,
    },
    {
        imgUrl:"/assets/games/13.webp",
        provider: "100HP GAMING",
        isHot: true,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/14.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/15.webp",
        provider: "MASCOT GAMING",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/16.webp",
        provider: "HACKSAW GAMING",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/17.webp",
        provider: "BELATRA",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/18.webp",
        provider: "BARBARA BANG",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/19.webp",
        provider: "TOPSPIN",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/20.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/21.webp",
        provider: "VELIPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/22.webp",
        provider: "TOPSPIN",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/23.webp",
        provider: "ONLYPLAY",
        isHot: true,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/24.webp",
        provider: "BARBARA BANG",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/25.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/26.webp",
        provider: "ONLYPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/27.webp",
        provider: "ONLYPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/28.webp",
        provider: "TOPSPIN",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/29.webp",
        provider: "100HP GAMING",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/30.webp",
        provider: "SMARTSOFT",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/31.webp",
        provider: "3 OAKS GAMING",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/32.webp",
        provider: "3 OAKS GAMING",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/33.webp",
        provider: "VOLTENT",
        isHot: false,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/34.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/35.webp",
        provider: "3 OAKS GAMING",
        isHot: true,
        isNew: false,
        isDiscounted: true,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/36.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/37.webp",
        provider: "100HP GAMING",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/38.webp",
        provider: "100HP GAMING",
        isHot: false,
        isNew: true,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/39.webp",
        provider: "BGAMING",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/40.webp",
        provider: "EVOPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/41.webp",
        provider: "EVOLUTION",
        isHot: true,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: false,
    },
    {
        imgUrl:"/assets/games/41.webp",
        provider: "EVOLUTION",
        isHot: true,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: false,
    },
    {
        imgUrl:"/assets/games/42.webp",
        provider: "EVOLUTION",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: false,
    },
    {
        imgUrl:"/assets/games/43.webp",
        provider: "MPLAY",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/44.webp",
        provider: "GALAXSYS",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
    {
        imgUrl:"/assets/games/45.webp",
        provider: "PLAYTECH",
        isHot: false,
        isNew: false,
        isDiscounted: false,
        isLive: false,
        hasDemo: true,
    },
];
